project:
  type: website
  output-dir: docs/
  render:
  - "*.qmd"

website:
  title: "Thamer's ML Blog"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/thamer-aldawood/
      - icon: github
        href: https://github.com/ThamerD
format:
  html:
    theme: darkly
    css: styles.css

# Use this to exclude execution of code chunks in the rendered output.
# execute:
#   eval: false


