<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Abeba Turi, Dhruv Garg, Ethan Fang, Thamer Aldawood">
<meta name="dcterms.date" content="2025-06-25">

<title>From Application to Graduation: Uncovering Patterns of Venture Success – Thamer’s ML Blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Thamer’s ML Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/thamer-aldawood/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ThamerD"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">From Application to Graduation: Uncovering Patterns of Venture Success</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Analysis</div>
                <div class="quarto-category">scikit-learn</div>
                <div class="quarto-category">ML Models</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Abeba Turi, Dhruv Garg, Ethan Fang, Thamer Aldawood </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">June 25, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link active" data-scroll-target="#executive-summary">Executive Summary</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data-science-methods" id="toc-data-science-methods" class="nav-link" data-scroll-target="#data-science-methods">Data Science Methods</a>
  <ul class="collapse">
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">Exploratory Data Analysis</a></li>
  <li><a href="#encoding-features" id="toc-encoding-features" class="nav-link" data-scroll-target="#encoding-features">Encoding features</a></li>
  <li><a href="#missing-data-imputation" id="toc-missing-data-imputation" class="nav-link" data-scroll-target="#missing-data-imputation">Missing Data Imputation</a></li>
  <li><a href="#evaluation-metrics" id="toc-evaluation-metrics" class="nav-link" data-scroll-target="#evaluation-metrics">Evaluation Metrics</a></li>
  <li><a href="#prediction-modeling" id="toc-prediction-modeling" class="nav-link" data-scroll-target="#prediction-modeling">Prediction Modeling</a></li>
  <li><a href="#similarity-modeling" id="toc-similarity-modeling" class="nav-link" data-scroll-target="#similarity-modeling">Similarity Modeling</a></li>
  <li><a href="#survival-analysis" id="toc-survival-analysis" class="nav-link" data-scroll-target="#survival-analysis">Survival Analysis</a></li>
  <li><a href="#dashboard" id="toc-dashboard" class="nav-link" data-scroll-target="#dashboard">Dashboard</a></li>
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility">Reproducibility</a></li>
  </ul></li>
  <li><a href="#results-and-data-product" id="toc-results-and-data-product" class="nav-link" data-scroll-target="#results-and-data-product">Results and Data Product</a>
  <ul class="collapse">
  <li><a href="#exploratory-data-analysis-1" id="toc-exploratory-data-analysis-1" class="nav-link" data-scroll-target="#exploratory-data-analysis-1">Exploratory Data Analysis</a></li>
  <li><a href="#predictive-modeling-performance" id="toc-predictive-modeling-performance" class="nav-link" data-scroll-target="#predictive-modeling-performance">Predictive Modeling Performance</a></li>
  <li><a href="#venture-similarity-analysis" id="toc-venture-similarity-analysis" class="nav-link" data-scroll-target="#venture-similarity-analysis">Venture Similarity Analysis</a></li>
  <li><a href="#survival-analysis-results" id="toc-survival-analysis-results" class="nav-link" data-scroll-target="#survival-analysis-results">Survival Analysis Results</a></li>
  <li><a href="#dashboard-architecture" id="toc-dashboard-architecture" class="nav-link" data-scroll-target="#dashboard-architecture">Dashboard Architecture</a>
  <ul class="collapse">
  <li><a href="#portfolio-snapshot" id="toc-portfolio-snapshot" class="nav-link" data-scroll-target="#portfolio-snapshot">Portfolio Snapshot</a></li>
  <li><a href="#venture-similarity-tool" id="toc-venture-similarity-tool" class="nav-link" data-scroll-target="#venture-similarity-tool">Venture Similarity Tool</a></li>
  <li><a href="#survival-analysis-module" id="toc-survival-analysis-module" class="nav-link" data-scroll-target="#survival-analysis-module">Survival Analysis Module</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#recommendations" id="toc-recommendations" class="nav-link" data-scroll-target="#recommendations">Recommendations</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="executive-summary" class="level1">
<h1>Executive Summary</h1>
<p>Creative Destruction Lab (CDL) is a non-profit startup accelerator that supports early stage science- and technology-based ventures through mentorship, resources, and investor networks to drive growth and commercialization. However, not all ventures that participate in the program graduate successfully. CDL aims to identify the factors contributing to a venture’s success and failure in the program to improve its selection process and provide better support. Drawing on a rich dataset of over <span class="math inline">\(5,000\)</span> ventures across multiple cohorts, we analyzed various features from four different data sets, including application records, founder education data, admitted venture logs, and longitudinal program updates (e.g., revenue, funding, headcount) to develop predictive models of venture progression. Yet, substantial missing data posed significant challenges in modeling dropout from the program.</p>
<p>This work benchmarked multiple machine learning models, including logistic regression, random forest, and gradient boosting classifiers, alongside a conventional Cox Proportional Hazards (PH) model. Performance was evaluated using the F1 score for classifiers and the concordance index (C-index) for survival models. Our findings indicate that machine learning models underperformed in predictive power despite advanced tuning due to data quality limitations, including significant missing data and noisy categorical inputs. In the survival analysis, the Cox PH model achieved moderate predictive performance (<span class="math inline">\(C\text{-}\text{index} \approx 0.61\)</span>). In addition to modeling, we developed an interactive dashboard to surface descriptive insights: graduation trends by sector and session, cohort-level revenue trajectories, geographic venture distribution, a venture similarity tool for benchmarking new applicants, and feature attribution plots showing top survival-impacting variables through a tornado plot. While predictive power was limited due to data gaps and unmeasured qualitative factors, the dashboard provides an interpretable tool to support evidence-based decision-making for venture selection and monitoring.</p>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Creative Destruction Lab (CDL), an established mentorship-driven accelerator program, is a non-profit organization that runs a program focused on supporting early stage science- and technology-based ventures by connecting them with experienced mentors and potential investors, <span class="citation" data-cites="cdlprogram">Creative Destruction Lab (<a href="#ref-cdlprogram" role="doc-biblioref">2025</a>)</span>. However, despite the program’s support, a significant number of ventures do not make it to graduation, defined as completing all four mentorship sessions. Mentors currently determine whether ventures continue or are dropped from the program based on their progress across sessions. This raises an important question: what factors determine whether a venture will succeed in the CDL program?</p>
<p>Picking on this question, the project focuses on building a data-driven foundation for answering this critical question. To support our modeling and venture profiling efforts, we drew on four key datasets including applications data: self-reported characteristics of ventures at intake (e.g., revenue, IP strategy, problem type), admitted data: internal program-level tags post-selection (e.g., stream, program year, geography), education data: detailing the academic background of founding teams, and Updates data: tracking revenue, funding, and team size across program sessions. In this work, a blend of machine learning and statistical models are applied (<span class="citation" data-cites="hallen2020">Hallen, Cohen, and Bingham (<a href="#ref-hallen2020" role="doc-biblioref">2020</a>)</span>, <span class="citation" data-cites="jongwoo2023">Jongwoo Kim (<a href="#ref-jongwoo2023" role="doc-biblioref">2023</a>)</span>, <span class="citation" data-cites="lin1989">Lin and Wei (<a href="#ref-lin1989" role="doc-biblioref">1989</a>)</span> and <span class="citation" data-cites="mona2024">Mona Razaghzadeh Bidgoli (<a href="#ref-mona2024" role="doc-biblioref">2024</a>)</span>). Given the modeling limitations resulting from data quality issues and unobserved factors like mentor impressions (<span class="citation" data-cites="cdlprogram">Creative Destruction Lab (<a href="#ref-cdlprogram" role="doc-biblioref">2025</a>)</span> and <span class="citation" data-cites="nejad2024">Nejad (<a href="#ref-nejad2024" role="doc-biblioref">2024</a>)</span>), pitch quality, or other qualitative signals, our dashboard heavily emphasizes on descriptive analytics and venture similarity comparisons within the dashboard.</p>
<p>The dashboard integrates all the analytical outputs in an interactive way that supports real-time venture profiling. This tool provides <span class="math inline">\((1)\)</span> granular venture profiling (through filters that let users drill down into individual ventures or specific cohorts, view key metrics like revenue over time, and analyze country-level distributions); <span class="math inline">\((2)\)</span> cohort comparisons (via dropdowns for session and stream, alongside visuals for graduation rate by Sector and global venture heatmap, which help contextualize venture performance across regions and industries); and <span class="math inline">\((3)\)</span> survival probability visualizations (which allows users to explore time-to-dropout predictions, highlighting venture-level risk profiles relative to historical patterns). This enables CDL stakeholders to move beyond binary predictions and instead leverage interpretable, data-informed guidance to support venture success across the mentorship lifecycle. CDL and stakeholders with access to the dashboard can use it to benchmark ventures, monitor cohort trends, and make informed decisions about early interventions and program design.</p>
<p>The remainder of this report is organized as follows: <span class="math inline">\(\text{Section 2}\)</span> outlines the data science methods highlighting the modeling techniques, feature engineering, evaluation metrics, and ethical considerations used to address the project’s scientific objectives; <span class="math inline">\(\text{Section 3}\)</span> covers the data product and results presenting our interactive venture profiling tool, summarizes key findings, and reflects on the design choices, use cases, and areas for future improvement and; <span class="math inline">\(\text{Section 4}\)</span> covers the conclusion and recommendations evaluating how well our data product meets the partner’s needs, and provides strategic guidance for potential enhancements and continued application.</p>
</section>
<section id="data-science-methods" class="level1">
<h1>Data Science Methods</h1>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<p>Exploratory data analysis was conducted using the following methods:</p>
<ul>
<li><strong>Descriptive Statistics</strong>: Mean, median, and standard deviation were calculated for numerical features to summarize their distributions.</li>
<li><strong>Missing Data Analysis</strong>: The proportion of missing values in each dataset was assessed to evaluate the extent of missingness and its potential impact on modeling.</li>
<li><strong>Correlation Analysis</strong>: Correlations between features and the target variable (graduation) were examined to identify potential predictors.</li>
<li><strong>Cohort Analysis</strong>: Data was analyzed across different cohorts to identify trends and patterns in venture performance over time.</li>
<li><strong>Graduation Rate Analysis</strong>: Graduation rates for different cohorts, sectors, and geographic locations were calculated to reveal trends and patterns in venture success.</li>
</ul>
</section>
<section id="encoding-features" class="level2">
<h2 class="anchored" data-anchor-id="encoding-features">Encoding features</h2>
<p>The datasets comprised categorical, ordinal, and numerical features. The following preprocessing steps were applied to prepare the data for modeling:</p>
<ol type="1">
<li><strong>Categorical Feature Encoding</strong>: One-hot encoding was employed to convert categorical features into numerical representations, enabling effective interpretation by the models. <span class="citation" data-cites="scikit-learn">(<a href="#ref-scikit-learn" role="doc-biblioref">Pedregosa et al. 2011</a>)</span></li>
<li><strong>Ordinal Feature Encoding</strong>: Label encoding was utilized for ordinal features to preserve the inherent order of categories during conversion to numerical values. <span class="citation" data-cites="scikit-learn">(<a href="#ref-scikit-learn" role="doc-biblioref">Pedregosa et al. 2011</a>)</span></li>
<li><strong>Numerical Feature Handling</strong>: Numerical features were retained in their original form, with appropriate scaling applied as required by the modeling process. <span class="citation" data-cites="scikit-learn">(<a href="#ref-scikit-learn" role="doc-biblioref">Pedregosa et al. 2011</a>)</span></li>
<li><strong>Free Text Feature Processing</strong>: Free text features in the updates dataset were processed using a combination of regular expressions and natural language processing techniques to extract relevant information such as revenue, funding, and headcount. This process involved:
<ul>
<li>The creation of a custom prompt to extract numerical values from the free text.</li>
<li>The use of the GPT-4.1 model via the OpenAI API to process the text and extract the required information. <span class="citation" data-cites="python openai2023gpt4">(<a href="#ref-python" role="doc-biblioref">Python Software Foundation 2023</a>; <a href="#ref-openai2023gpt4" role="doc-biblioref">OpenAI 2023</a>)</span></li>
</ul></li>
</ol>
<p>Alternative encoding methods, such as target encoding or embeddings, could be explored to better capture information from high-cardinality categorical features. However, these approaches were not implemented due to their added complexity compared to these simpler methods which were fairly effective for our dataset.</p>
</section>
<section id="missing-data-imputation" class="level2">
<h2 class="anchored" data-anchor-id="missing-data-imputation">Missing Data Imputation</h2>
<p>Given the relatively small size of the data and the proportion of missingness, the removal of rows containing missing values was deemed unsuitable. Instead, two imputation techniques were explored:</p>
<ol type="1">
<li><strong>Simple Imputation</strong>
<ul>
<li>Missing values were filled using the mean, median, or mode of the respective feature, or with a constant value.</li>
<li>While this approach is straightforward and computationally efficient, it may introduce bias if the missingness is not random <span class="citation" data-cites="Little2002">(<a href="#ref-Little2002" role="doc-biblioref">Little and Rubin 2002</a>)</span>.</li>
</ul></li>
<li><strong>Iterative Imputation</strong>
<ul>
<li>Machine learning models were employed to estimate missing values based on the observed features in the dataset.</li>
<li>Although more complex and time-intensive, this method can yield more accurate imputations when the assumption of missing at random does not hold <span class="citation" data-cites="Jerez2010 Buuren2011">(<a href="#ref-Jerez2010" role="doc-biblioref">Jerez et al. 2010</a>; <a href="#ref-Buuren2011" role="doc-biblioref">Buuren and Groothuis-Oudshoorn 2011</a>)</span>.</li>
</ul></li>
</ol>
<p>Alternative advanced imputation methods, such as k-nearest neighbors (KNN) imputation and matrix factorization, could be considered, but were not implemented due to increased complexity and limited expected benefit given the dataset size.</p>
</section>
<section id="evaluation-metrics" class="level2">
<h2 class="anchored" data-anchor-id="evaluation-metrics">Evaluation Metrics</h2>
<p>To rigorously assess model performance in identifying the factors influencing venture success within the CDL program, evaluation metrics were selected based on their suitability towards our objectives and data characteristics. Given the binary classification task and the presence of class imbalance, the F1 score was adopted as the primary metric, as it effectively balances precision and recall, providing a more informative measure than accuracy alone <span class="citation" data-cites="Lipton2014">(<a href="#ref-Lipton2014" role="doc-biblioref">Lipton, Elkan, and Naryanaswamy 2014</a>)</span>. For survival analysis, the concordance index (C-index) was utilized to quantify the model’s ability to correctly rank event times and is well-suited for censored data <span class="citation" data-cites="Uno2011">(<a href="#ref-Uno2011" role="doc-biblioref">Uno et al. 2011</a>)</span>. These metrics were chosen to help CDL minimize both false positives (ventures incorrectly expected to succeed) and false negatives (ventures overlooked despite high potential) in selection decisions, while also supporting session-level risk monitoring and targeted intervention through survival risk ranking.</p>
</section>
<section id="prediction-modeling" class="level2">
<h2 class="anchored" data-anchor-id="prediction-modeling">Prediction Modeling</h2>
<p>A series of machine learning models was implemented to predict venture graduation, with each model selected for its strengths in addressing the complexities of the dataset. Training was conducted exclusively on data collected prior to ventures being admitted into the CDL program. This approach was adopted to align with CDL’s objective of identifying factors associated with venture success before program initiation.</p>
<p>The target variable was defined as the graduation status of a venture, where graduation was determined by the completion of all four mentorship sessions in the CDL program. The following models were implemented:</p>
<ol type="1">
<li><strong>Dummy Classifier</strong>: Used as a baseline to establish the minimum performance level. It helps us determine if more complex models provide meaningful improvements over random or majority-class predictions. <span class="citation" data-cites="scikit-learn">(<a href="#ref-scikit-learn" role="doc-biblioref">Pedregosa et al. 2011</a>)</span></li>
<li><strong>Logistic Regression</strong>: Chosen for its simplicity, interpretability, and effectiveness in binary classification tasks. It provides a strong baseline and helps identify linear relationships between features and graduation outcomes. <span class="citation" data-cites="scikit-learn">(<a href="#ref-scikit-learn" role="doc-biblioref">Pedregosa et al. 2011</a>)</span></li>
<li><strong>Hist Gradient Boosting Classifier</strong>: Selected for its ability to handle missing values natively and capture complex, non-linear relationships in the data. Its ensemble approach often yields higher accuracy on structured datasets. <span class="citation" data-cites="scikit-learn">(<a href="#ref-scikit-learn" role="doc-biblioref">Pedregosa et al. 2011</a>)</span></li>
<li><strong>XGBoost Classifier</strong>: Included due to its reputation for high performance and efficiency in classification problems. It is robust to overfitting and can handle imbalanced datasets, making it suitable for our data characteristics. <span class="citation" data-cites="chen2016">(<a href="#ref-chen2016" role="doc-biblioref">Chen and Guestrin 2016</a>)</span></li>
</ol>
<p>Feature selection was performed using recursive feature elimination with cross-validation (RFECV) to identify the most informative predictors. This approach enabled the retention of features that contributed most to model performance, improving both interpretability and generalizability of the final model. <span class="citation" data-cites="scikit-learn">(<a href="#ref-scikit-learn" role="doc-biblioref">Pedregosa et al. 2011</a>)</span></p>
<p>Advanced modeling techniques such as deep learning or stacking ensembles could potentially improve predictive performance, especially if more data were available. However, these approaches require larger datasets, increased computational resources, and careful tuning to avoid overfitting. Given the limited sample size and the need for interpretability, these improvements were not implemented in this analysis.</p>
</section>
<section id="similarity-modeling" class="level2">
<h2 class="anchored" data-anchor-id="similarity-modeling">Similarity Modeling</h2>
<p>Similarity modeling was implemented using the NearestNeighbors algorithm from scikit-learn, which identifies the most similar ventures by computing pairwise Euclidean distances on selected features. To ensure missing values did not distort similarity calculations, a simple imputer replaced them with a constant negative value that was chosen because it falls outside the range of valid feature values, clearly signaling missingness to the model. Numeric features were then standardized using a scaler to ensure fair distance comparisons. The fitted model was saved as a pickle file, enabling seamless integration and dynamic loading within the dashboard application. Instance-based learning algorithms, such as nearest neighbor approaches, have been widely used for comparative assessments in machine learning <span class="citation" data-cites="Aha1991">(<a href="#ref-Aha1991" role="doc-biblioref">Aha, Kibler, and Albert 1991</a>)</span>.</p>
</section>
<section id="survival-analysis" class="level2">
<h2 class="anchored" data-anchor-id="survival-analysis">Survival Analysis</h2>
<p>Survival analysis was conducted using the Cox Proportional Hazards Model from the lifelines package to estimate the risk of venture dropout over time. After preprocessing and imputation, feature selection was performed by removing variables with low variance and high multicollinearity, using variance thresholding and variance inflation factor (VIF) analysis. This approach ensured that only informative and independent features were retained for modeling. The model was then trained to predict time until dropout, enabling the estimation of survival probabilities for each venture throughout the program. This model was also saved as a pickle file for integration into the dashboard application. <span class="citation" data-cites="lin1989 lifelines">(<a href="#ref-lin1989" role="doc-biblioref">Lin and Wei 1989</a>; <a href="#ref-lifelines" role="doc-biblioref">Davidson-Pilon 2019</a>)</span></p>
</section>
<section id="dashboard" class="level2">
<h2 class="anchored" data-anchor-id="dashboard">Dashboard</h2>
<p>An interactive dashboard was implemented using the Dash framework to enable exploration of venture data and model outputs. Modular Python scripts were used to load processed data, apply models, and generate visualizations with Plotly. Callback functions allowed users to dynamically filter and view results by cohort or venture attributes. This approach ensured that analytical outputs could be explored interactively and consistently with the underlying data science workflow. <span class="citation" data-cites="plotly dash">(<a href="#ref-plotly" role="doc-biblioref">P. T. Inc. 2015</a>; <a href="#ref-dash" role="doc-biblioref">Parmer, Johnson, and Plotly team 2017</a>)</span></p>
</section>
<section id="reproducibility" class="level2">
<h2 class="anchored" data-anchor-id="reproducibility">Reproducibility</h2>
<p>To facilitate reproducibility, a Docker container was created to encapsulate the entire data science workflow, including data preprocessing, feature engineering, model training, and evaluation. This container ensures that all dependencies and configurations are consistent across different environments, allowing for seamless execution of the analysis. This approach enables users to easily rerun the entire workflow and monitor changes in model performance or data characteristics over time. <span class="citation" data-cites="docker">(<a href="#ref-docker" role="doc-biblioref">D. Inc. 2013</a>)</span></p>
</section>
</section>
<section id="results-and-data-product" class="level1">
<h1>Results and Data Product</h1>
<section id="exploratory-data-analysis-1" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis-1">Exploratory Data Analysis</h2>
<p>Analysis of 5,047 ventures admitted to CDL between 2013 and 2024 revealed that venture success lacks a single dominant predictive factor, as no feature has a correlation coefficient larger than 0.06 (<a href="#fig-correlations" class="quarto-xref">Figure&nbsp;1</a>). It also revealed that missing data is significantly prevalent in many key features (<a href="#fig-missingness" class="quarto-xref">Figure&nbsp;2</a>).</p>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="1">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-correlations" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-correlations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/top_feature_correlations.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-correlations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Top 20 features most correlated with graduation
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-missingness" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-missingness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/applications_missingness.png" class="img-fluid figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-missingness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Proportion of missing values in the Applications dataset
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="predictive-modeling-performance" class="level2">
<h2 class="anchored" data-anchor-id="predictive-modeling-performance">Predictive Modeling Performance</h2>
<p><a href="#tbl-model-performance" class="quarto-xref">Table&nbsp;1</a> summarizes the predictive modeling results. Logistic regression, HistGradientBoosting, and XGBoost were evaluated using both simple and iterative imputation strategies. HistGradientBoosting was also tested without imputation, leveraging its ability to handle missing data natively. The highest validation F1 score achieved was 0.32.</p>
<div id="tbl-model-performance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-performance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Model Performance Metrics
</figcaption>
<div aria-describedby="tbl-model-performance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th>Metric</th>
<th>Mean</th>
<th>Std</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>dummy_clf</td>
<td>train_accuracy</td>
<td>0.665</td>
<td>0</td>
</tr>
<tr class="even">
<td>dummy_clf</td>
<td>validation_accuracy</td>
<td>0.665</td>
<td>0.001</td>
</tr>
<tr class="odd">
<td>dummy_clf</td>
<td>train_f1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>dummy_clf</td>
<td>validation_f1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>hgb_nonimpute</td>
<td>train_accuracy</td>
<td>0.849</td>
<td>0.005</td>
</tr>
<tr class="even">
<td>hgb_nonimpute</td>
<td>validation_accuracy</td>
<td>0.645</td>
<td>0.026</td>
</tr>
<tr class="odd">
<td>hgb_nonimpute</td>
<td>train_f1</td>
<td>0.736</td>
<td>0.007</td>
</tr>
<tr class="even">
<td>hgb_nonimpute</td>
<td>validation_f1</td>
<td>0.307</td>
<td>0.038</td>
</tr>
<tr class="odd">
<td>LogisticRegression_simple</td>
<td>train_accuracy</td>
<td>0.755</td>
<td>0.005</td>
</tr>
<tr class="even">
<td>LogisticRegression_simple</td>
<td>validation_accuracy</td>
<td>0.635</td>
<td>0.012</td>
</tr>
<tr class="odd">
<td>LogisticRegression_simple</td>
<td>train_f1</td>
<td>0.516</td>
<td>0.014</td>
</tr>
<tr class="even">
<td>LogisticRegression_simple</td>
<td>validation_f1</td>
<td>0.263</td>
<td>0.027</td>
</tr>
<tr class="odd">
<td>XGB_simple</td>
<td>train_accuracy</td>
<td>0.870</td>
<td>0.005</td>
</tr>
<tr class="even">
<td>XGB_simple</td>
<td>validation_accuracy</td>
<td>0.631</td>
<td>0.015</td>
</tr>
<tr class="odd">
<td>XGB_simple</td>
<td>train_f1</td>
<td>0.776</td>
<td>0.010</td>
</tr>
<tr class="even">
<td>XGB_simple</td>
<td>validation_f1</td>
<td>0.285</td>
<td>0.007</td>
</tr>
<tr class="odd">
<td>HGB_simple</td>
<td>train_accuracy</td>
<td>0.857</td>
<td>0.004</td>
</tr>
<tr class="even">
<td>HGB_simple</td>
<td>validation_accuracy</td>
<td>0.645</td>
<td>0.013</td>
</tr>
<tr class="odd">
<td>HGB_simple</td>
<td>train_f1</td>
<td>0.748</td>
<td>0.009</td>
</tr>
<tr class="even">
<td>HGB_simple</td>
<td>validation_f1</td>
<td>0.299</td>
<td>0.023</td>
</tr>
<tr class="odd">
<td>LogisticRegression_iter</td>
<td>train_accuracy</td>
<td>0.755</td>
<td>0.005</td>
</tr>
<tr class="even">
<td>LogisticRegression_iter</td>
<td>validation_accuracy</td>
<td>0.634</td>
<td>0.014</td>
</tr>
<tr class="odd">
<td>LogisticRegression_iter</td>
<td>train_f1</td>
<td>0.517</td>
<td>0.012</td>
</tr>
<tr class="even">
<td>LogisticRegression_iter</td>
<td>validation_f1</td>
<td>0.262</td>
<td>0.032</td>
</tr>
<tr class="odd">
<td>XGB_iter</td>
<td>train_accuracy</td>
<td>0.905</td>
<td>0.010</td>
</tr>
<tr class="even">
<td>XGB_iter</td>
<td>validation_accuracy</td>
<td>0.622</td>
<td>0.018</td>
</tr>
<tr class="odd">
<td>XGB_iter</td>
<td>train_f1</td>
<td>0.843</td>
<td>0.019</td>
</tr>
<tr class="even">
<td>XGB_iter</td>
<td>validation_f1</td>
<td>0.285</td>
<td>0.025</td>
</tr>
<tr class="odd">
<td>HGB_iter</td>
<td>train_accuracy</td>
<td>0.885</td>
<td>0.007</td>
</tr>
<tr class="even">
<td>HGB_iter</td>
<td>validation_accuracy</td>
<td>0.632</td>
<td>0.007</td>
</tr>
<tr class="odd">
<td>HGB_iter</td>
<td>train_f1</td>
<td>0.806</td>
<td>0.013</td>
</tr>
<tr class="even">
<td>HGB_iter</td>
<td>validation_f1</td>
<td>0.292</td>
<td>0.022</td>
</tr>
<tr class="odd">
<td>XGB_tuned</td>
<td>train_accuracy</td>
<td>0.966</td>
<td>0.003</td>
</tr>
<tr class="even">
<td>XGB_tuned</td>
<td>validation_accuracy</td>
<td>0.634</td>
<td>0.013</td>
</tr>
<tr class="odd">
<td>XGB_tuned</td>
<td>train_f1</td>
<td>0.949</td>
<td>0.004</td>
</tr>
<tr class="even">
<td>XGB_tuned</td>
<td>validation_f1</td>
<td>0.372</td>
<td>0.021</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<!-- Can add the new results through this code but we have commented it for our current results to not vary. -->
<!-- ```{python}
#| label: tbl-model-performance
#| tbl-cap: "Model Performance Metrics"

import pandas as pd
df = pd.read_csv("../../src/models/results/graduation_prediction_model_cv_results.csv")
df = df.rename({'Unnamed: 0': 'Model', 
'Unnamed: 1': 'Metric', 
'mean': 'Mean',
'std': 'Std'}, axis = 1)
df
``` -->
</section>
<section id="venture-similarity-analysis" class="level2">
<h2 class="anchored" data-anchor-id="venture-similarity-analysis">Venture Similarity Analysis</h2>
<p>As seen in <a href="#fig-similarity-tool" class="quarto-xref">Figure&nbsp;4</a>, the similarity tool allows users to input seven key characteristics: industry, problem domain, IP strategy, technology readiness, team size, revenue, and funding status. Then, the tool returns the top 5 most similar ventures from the CDL portfolio and showcases the most similar features as well as the outcomes of the ventures.</p>
</section>
<section id="survival-analysis-results" class="level2">
<h2 class="anchored" data-anchor-id="survival-analysis-results">Survival Analysis Results</h2>
<p>Cox Proportional Hazards modeling identified Sessions 2-3 as the highest dropout risk period, with a concordance index of 0.61. Sector-specific survival patterns emerged, suggesting differential alignment between venture types and CDL’s program structure.</p>
</section>
<section id="dashboard-architecture" class="level2">
<h2 class="anchored" data-anchor-id="dashboard-architecture">Dashboard Architecture</h2>
<p>Analytical outputs were integrated into an interactive web-based dashboard with three modules described below. The platform enables dynamic exploration supporting evidence-based decision-making while augmenting existing evaluation processes.</p>
<section id="portfolio-snapshot" class="level3">
<h3 class="anchored" data-anchor-id="portfolio-snapshot">Portfolio Snapshot</h3>
<div id="fig-portfolio-snapshot" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-portfolio-snapshot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/portfolio_snapshot.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-portfolio-snapshot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Portfolio Snapshot Dashboard
</figcaption>
</figure>
</div>
<p>The Portfolio Snapshot module provides aggregate trend visualization across temporal, sectoral, and geographic dimensions with interactive filtering capabilities. The choropleth map showcases venture global distribution and enables filtering by country. The line chart showcases several key growth metrics (revenue, funding, employee count) over sessions. The bar chart visualizes graduation rates by sector.</p>
</section>
<section id="venture-similarity-tool" class="level3">
<h3 class="anchored" data-anchor-id="venture-similarity-tool">Venture Similarity Tool</h3>
<div id="fig-similarity-tool" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-similarity-tool-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/venture_similarity.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-similarity-tool-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Venture Similarity Tool Dashboard
</figcaption>
</figure>
</div>
<p>The Venture Similarity Tool enables real-time benchmarking by comparing new ventures against historical CDL portfolio data.</p>
</section>
<section id="survival-analysis-module" class="level3">
<h3 class="anchored" data-anchor-id="survival-analysis-module">Survival Analysis Module</h3>
<div id="fig-survival-analysis" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-pos="H">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-survival-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/survival_model.png" class="img-fluid figure-img" data-fig-pos="H">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-survival-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Survival Analysis Dashboard
</figcaption>
</figure>
</div>
<p>The Survival Analysis module visualizes dropout risk profiles at both cohort and individual venture levels.</p>
<p>The data product was developed to integrate the most reliable analytical outputs specifically, similarity and survival analyses into a single tool that supports CDL’s strategic goals of selection, monitoring, and risk management.</p>
</section>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>The exploratory data analysis indicated that venture success within the CDL program is shaped by a complex combination of factors, with no single feature emerging as a dominant predictor of graduation. The diversity of the CDL portfolio, which includes ventures from fields such as artificial intelligence and quantum computing, further contributes to this complexity.</p>
<p>Data quality was identified as a significant limitation. Substantial missingness was observed in self-reported financial metrics, particularly for revenue, funding, and team size, as ventures were often reluctant to disclose sensitive information. In contrast, structured categorical variables—such as sector, geography, and prototype readiness—were found to be more reliable for modeling. Nevertheless, modeling results demonstrated that these structured features alone were insufficient for accurately predicting graduation outcomes, highlighting the continued importance of qualitative assessments in CDL’s decision-making process.</p>
<p>As summarized in <a href="#tbl-model-performance" class="quarto-xref">Table&nbsp;1</a>, the best-performing prediction model achieved a validation F1 score of 0.372, indicating that accurate prediction of venture graduation remains challenging. The much higher F1 score observed on the training set (0.949) suggests overfitting rather than genuine predictive capability. Attempts to improve generalizability through model tuning and feature selection resulted in only marginal gains. Several factors likely contributed to these limitations. Venture graduation is influenced by numerous unobservable variables that are not captured in the available data. Graduation decisions are made by different mentors, each with their own biases and criteria, for whom no data are available. The dataset is relatively small, with 3,536 rows in the applications dataset, and a large proportion of columns contain missing data. Additionally, the available data are self-reported, raising concerns about accuracy.</p>
<p>Given these constraints, further model optimization was deemed unlikely to yield substantial improvements. As a result, similarity modeling was adopted as an alternative approach to support venture evaluation. This method may offer advantages because it does not rely on the same predictive assumptions as traditional models and can leverage CDL’s qualitative knowledge in conjunction with structured data, enabling a more nuanced assessment of venture characteristics and outcomes.</p>
<p>In addition, survival analysis using the Cox Proportional Hazards Model was implemented to provide insights into venture retention and dropout risk over time. This approach allows for the analysis of time-to-event data (such as graduation) while accounting for covariates including industry, technology stage, and revenue, and can help identify factors influencing the likelihood of graduation at various stages of the program.</p>
<p>All models and analytical pipelines have been delivered in a reproducible format, with the expectation that their performance will improve as more high-quality data become available. At present, the dashboard offers CDL a comprehensive overview of venture characteristics, graduation rates, and dropout risks, supporting data-driven decision-making and strategic support for ventures throughout the program.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This capstone project analyzed the progression of ventures through the Creative Destruction Lab (CDL) program, from application to graduation. Data preprocessing, feature engineering, and machine learning models such as logistic regression and XGBoost were used to identify factors influencing venture success. However, predictive models showed limited generalization, with a maximum validation F1 score of 0.372, highlighting the complexity of predicting graduation outcomes.</p>
<p>To address these challenges, a similarity modeling framework was implemented, enabling comparative assessments between new and historical ventures. Survival analysis using the Cox Proportional Hazards model further provided session-specific survival probabilities and identified key dropout risks.</p>
<p>All analytical results were consolidated into an interactive dashboard, offering users comprehensive venture analytics and comparative visualizations. This dashboard enhances CDL stakeholders’ ability to monitor and support venture progress, while its effectiveness remains dependent on the quality and completeness of available data.</p>
</section>
<section id="recommendations" class="level1">
<h1>Recommendations</h1>
<p>Based on the findings of this project, several recommendations are proposed to strengthen CDL’s venture selection and monitoring processes. First, integrating the similarity modeling framework into mentor matching could enable more relevant pairings, increasing the likelihood of venture success through better aligned guidance. Survival analysis should also be incorporated into ongoing risk monitoring to help identify dropout risks early and support timely interventions. To address data quality challenges, CDL could consider redesigning application forms to standardize key fields particularly those related to financial metrics and make their completion mandatory. Building real-time data pipelines would ensure that dashboards reflect the most current venture metrics, improving the accuracy and timeliness of monitoring. Finally, collecting structured qualitative feedback, including mentor evaluations and founder pitch assessments, would provide additional context to enhance future predictive and comparative analyses.</p>
</section>
<section id="references" class="level1">




</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Aha1991" class="csl-entry" role="listitem">
Aha, David W., Dennis Kibler, and Marc K. Albert. 1991. <span>“Instance-Based Learning Algorithms.”</span> <em>Machine Learning</em> 6 (1).
</div>
<div id="ref-Buuren2011" class="csl-entry" role="listitem">
Buuren, S. van, and K. Groothuis-Oudshoorn. 2011. <span>“Mice: Multivariate Imputation by Chained Equations in r.”</span> <em>Journal of Statistical Software</em> 45 (3).
</div>
<div id="ref-chen2016" class="csl-entry" role="listitem">
Chen, Tianqi, and Carlos Guestrin. 2016. <span>“<span>XGBoost</span>: A Scalable Tree Boosting System.”</span> ACM.
</div>
<div id="ref-cdlprogram" class="csl-entry" role="listitem">
Creative Destruction Lab. 2025. <span>“Programs.”</span> <a href="https://creativedestructionlab.com/program/" class="uri">https://creativedestructionlab.com/program/</a>.
</div>
<div id="ref-lifelines" class="csl-entry" role="listitem">
Davidson-Pilon, Cameron. 2019. <span>“Lifelines: Survival Analysis in Python.”</span> <a href="https://github.com/CamDavidsonPilon/lifelines" class="uri">https://github.com/CamDavidsonPilon/lifelines</a>.
</div>
<div id="ref-hallen2020" class="csl-entry" role="listitem">
Hallen, Benjamin L., Susan L. Cohen, and Christopher B. Bingham. 2020. <span>“Do Accelerators Work? If so, How?”</span> <em>Organization Science</em> 31 (2): 378–414. <a href="https://doi.org/10.1287/orsc.2019.1304">https://doi.org/10.1287/orsc.2019.1304</a>.
</div>
<div id="ref-docker" class="csl-entry" role="listitem">
Inc., Docker. 2013. <span>“Docker: Enterprise Container Platform.”</span> <a href="https://www.docker.com" class="uri">https://www.docker.com</a>.
</div>
<div id="ref-plotly" class="csl-entry" role="listitem">
Inc., Plotly Technologies. 2015. <span>“Plotly: Python Graphing Library.”</span> <a href="https://plotly.com/python/" class="uri">https://plotly.com/python/</a>.
</div>
<div id="ref-Jerez2010" class="csl-entry" role="listitem">
Jerez, J. M., I. Molina, P. J. García-Laencina, E. Alba, N. Ribelles, M. Martín, and L. Franco. 2010. <span>“Missing Data Imputation Using Statistical and Machine Learning Methods in a Real Breast Cancer Problem.”</span> <em>Artificial Intelligence in Medicine</em> 50 (2).
</div>
<div id="ref-jongwoo2023" class="csl-entry" role="listitem">
Jongwoo Kim, Youngjung Geum, Hongil Kim. 2023. <span>“How to Succeed in the Market? Predicting Startup Success Using a Machine Learning Approach.”</span>
</div>
<div id="ref-lin1989" class="csl-entry" role="listitem">
Lin, D. Y., and L. J. Wei. 1989. <span>“The Robust Inference for the Cox Proportional Hazards Model.”</span> <em>Journal of the American Statistical Association</em> 84 (408): 1074–78. <a href="https://doi.org/10.1080/01621459.1989.10478874">https://doi.org/10.1080/01621459.1989.10478874</a>.
</div>
<div id="ref-Lipton2014" class="csl-entry" role="listitem">
Lipton, Zachary C., Charles Elkan, and Balakrishnan Naryanaswamy. 2014. <span>“Thresholding Classifiers to Maximize F1 Score.”</span> <a href="https://arxiv.org/abs/1402.1892">https://arxiv.org/abs/1402.1892</a>.
</div>
<div id="ref-Little2002" class="csl-entry" role="listitem">
Little, R. J. A., and D. B. Rubin. 2002. <em>Statistical Analysis with Missing Data</em>. Wiley.
</div>
<div id="ref-mona2024" class="csl-entry" role="listitem">
Mona Razaghzadeh Bidgoli, Mehdi Goodarzi, Iman Raeesi Vanani. 2024. <span>“Predicting the Success of Startups Using a Machine Learning Approach.”</span>
</div>
<div id="ref-nejad2024" class="csl-entry" role="listitem">
Nejad, M. H. 2024. <span>“A Structural Model of Mentorship in Startup Accelerators: Matching, Learning, and Value Creation.”</span>
</div>
<div id="ref-openai2023gpt4" class="csl-entry" role="listitem">
OpenAI. 2023. <span>“GPT-4 Technical Report.”</span> <a href="https://openai.com/research/gpt-4" class="uri">https://openai.com/research/gpt-4</a>.
</div>
<div id="ref-dash" class="csl-entry" role="listitem">
Parmer, Chris, Alex Johnson, and the Plotly team. 2017. <span>“Dash: A Python Framework for Building Reactive Web Applications.”</span> <a href="https://dash.plotly.com/" class="uri">https://dash.plotly.com/</a>.
</div>
<div id="ref-scikit-learn" class="csl-entry" role="listitem">
Pedregosa, Fabian, Gaël Varoquaux, Alexandre Gramfort, Vincent Michel, Bertrand Thirion, Olivier Grisel, Mathieu Blondel, et al. 2011. <span>“Scikit-Learn: Machine Learning in Python.”</span> <em>Journal of Machine Learning Research</em> 12.
</div>
<div id="ref-python" class="csl-entry" role="listitem">
Python Software Foundation. 2023. <span>“Python Language Reference, Version 3.11.”</span> <a href="https://www.python.org/" class="uri">https://www.python.org/</a>.
</div>
<div id="ref-Uno2011" class="csl-entry" role="listitem">
Uno, Hajime, Lu Tian, Tianxi Cai, Isaac S. Kohane, and Lee-Jen Wei. 2011. <span>“On the c-Statistics for Evaluating Overall Adequacy of Risk Prediction Procedures with Censored Survival Data.”</span> <em>Statistics in Medicine</em> 30 (10).
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>